# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
User.destroy_all
u1 = User.new(name: "ash", email: "ash@catch.com", dna: "brat good", fitbit_token: "fitbit please connect")
u1.save!

u2 = User.new(name: "misty", email: "misty@catch.com", dna: "funky pairs", fitbit_token: "fitbit connected")
u2.save!

u3 = User.new(name: "john doe", email: "test@lala.com", dna: "pair says good", fitbit_token: "Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI1RFJCMjQiLCJhdWQiOiIyMkNSS1QiLCJpc3MiOiJGaXRiaXQiLCJ0eXAiOiJhY2Nlc3NfdG9rZW4iLCJzY29wZXMiOiJ3aHIgd251dCB3cHJvIHdzbGUgd3dlaSB3c29jIHdhY3Qgd3NldCB3bG9jIiwiZXhwIjoxNTI1NjIxMTc3LCJpYXQiOjE1MjU1OTIzNzd9.oadFv1CPNV9xXe5XMpDGtfJAZgbabzbffpgqaG9T-sk")
u3.save!

User.GetWaterGoal(u3.id)
User.GetSleepGoal(u3.id)
User.PullFitBitGoals(u3.id)

Allelean.destroy_all
a0 = Allelean.new(name: "Base Egg", slug: "basic-egg", photo: "ic_egg.xml", web_photo: "egg.svg", multiplier_steps: 0.1, multiplier_calories: 0.1, multiplier_sleep: 0.1, multiplier_water: 0.1)
a0.save!

a3 = Allelean.new(name: "Monkey Boss", slug: "monkey-boss", photo: "ic_monkey_boss.xml", web_photo: "monkey_boss.svg",evolve_id: nil, multiplier_steps: 1, multiplier_calories: 1, multiplier_sleep: 1, multiplier_water: 1)
a3.save!

a2 = Allelean.new(name: "Monkey Gremling", slug: "monkey-gremling", photo: "ic_monkey_gremling.xml", web_photo: "monkey_gremling.svg", evolve_id: a3.id, multiplier_steps: 1, multiplier_calories: 1, multiplier_sleep: 1, multiplier_water: 1)
a2.save!

a1 = Allelean.new(name: "Monkey Base", slug: "monkey-base", photo: "ic_monkey.xml", web_photo: "monkey.svg", evolve_id: a2.id, multiplier_steps: 10000, multiplier_calories: 1000, multiplier_sleep: 1, multiplier_water: 10)
a1.save!

a4 = Allelean.new(name: "Fat Cat", slug: "fat-cat", photo: "ic_cat.xml", web_photo: "cat.svg", multiplier_steps: 0.3, multiplier_calories: 0.3, multiplier_sleep: 2, multiplier_water: 1)
a4.save!

a5 = Allelean.new(name: "Up Dog", slug: "up-dog", photo: "ic_dog.xml", web_photo: "dog.svg", multiplier_steps: 1.1, multiplier_calories: 1.1, multiplier_sleep: 1.1, multiplier_water: 1.1)
a5.save!

a6 = Allelean.new(name: "Gym Rat", slug: "gym-rat", photo: "ic_gym_rat.xml", web_photo: "gym_rat.svg", multiplier_steps: 1.5, multiplier_calories: 1.5, multiplier_sleep: 1, multiplier_water: 1.5)
a6.save!

a7 = Allelean.new(name: "Night Owl", slug: "night-owl", photo: "ic_owl.xml", web_photo: "owl.svg", multiplier_steps: 1.25, multiplier_calories: 1, multiplier_sleep: 1.5, multiplier_water: 0.5)
a7.save!

a8 = Allelean.new(name: "Mythical Unicorn", slug: "mythical-unicorn", photo: "ic_unicorn.xml", web_photo: "unicorn.svg", multiplier_steps: 3, multiplier_calories: 3, multiplier_sleep: 3, multiplier_water: 3)
a8.save!

a9 = Allelean.new(name: "Fit Whale", slug: "fit-whale", photo: "ic_whale.xml", web_photo: "whale.svg", multiplier_steps: 1.3, multiplier_calories: 1.3, multiplier_sleep: 1, multiplier_water: 2)
a9.save!

Stable.destroy_all
Stable.new(user_id: u1.id, allelean_id: a4.id, is_active: true, level: 1, exp: 50, aquired_date: Time.now.utc).save!

Stable.new(user_id: u2.id, allelean_id: a7.id, is_active: true, exp: 100, level: 3, aquired_date: Time.now.utc).save!

Stable.new(user_id: u3.id, allelean_id: a0.id, is_active: true, exp: 10, level: 0, aquired_date: Time.now.utc).save!

HelixInfo.destroy_all
HelixInfo.new(gene: "Gene", variant: "Variant", a1: "A1", a2: "A2", trait: "Trait Name", insight: "Insight", recommend: "Action / Recommendation", impact: "Impact", frequency: "Frequency", references: "References").save!
HelixInfo.new(gene: "MCM6/ LCT", variant: "rs4988235", a1: "G", a2: "G", trait: "Lactose Tolerance", insight: "GG individuals are more likely to be lactose intolerant.", recommend: "These individuals should avoid consuming dairy products that contain lactose.", impact: "HIGH. Environment plays a small role (and individuals who are mildly lactose intolerant may have been consuming dairy without realizing the negative effects).", frequency: "70%", references: "11788828").save!
HelixInfo.new(gene: "MCM6/ LCT", variant: "rs4988235", a1: "G", a2: "A", trait: "Lactose Tolerance", insight: "GA individuals are more likely to be tolerant of lactose.", recommend: "These individuals should be able to consume dairy without side effects.", impact: "HIGH. Environment plays a small role (and individuals who are mildly lactose intolerant may have been consuming dairy without realizing the negative effects).", frequency: "27%", references: "11788828").save!
HelixInfo.new(gene: "MCM6/ LCT", variant: "rs4988235", a1: "A", a2: "A", trait: "Lactose Tolerance", insight: "AA individuals are more likely to be tolerant of lactose.", recommend: "These individuals should be able to consume dairy without side effects.", impact: "HIGH. Environment plays a small role (and individuals who are mildly lactose intolerant may have been consuming dairy without realizing the negative effects).", frequency: "3%", references: "11788828").save!
HelixInfo.new(gene: "APOA2", variant: "rs5082", a1: "G", a2: "G", trait: "Saturated Fat metabolism", insight: "GG individuals are more likely to gain more weight when their diet is high in saturated fats.", recommend: "These individuals should pay special attention to keeping their daily consumption of saturated fat below 22g/day.", impact: "LOW. Saturated fat consumption and this specific genetic variant are only a small component of BMI. Other healthy life choices are important for maintaining a healthy weight.", frequency: "5.60%", references: "24108135, 26210798, 19901143").save!
HelixInfo.new(gene: "APOA2", variant: "rs5082", a1: "G", a2: "A", trait: "Saturated Fat metabolism", insight: "GA individuals are more likely to have similar weight regardless of the amount of saturated fat in their diet", recommend: "These individuals will not see weight loss benefits from lowering their saturated fat intake.", impact: "LOW. Saturated fat consumption and this specific genetic variant are only a small component of BMI. Other healthy life choices are important for maintaining a healthy weight.", frequency: "36.20%", references: "24108135, 26210798, 19901143").save!
HelixInfo.new(gene: "APOA2", variant: "rs5082", a1: "A", a2: "A", trait: "Saturated Fat metabolism", insight: "AA individuals are more likely to have similar weight regardless of the amount of saturated fat in their diet.", recommend: "These individuals will not see weight loss benefits from lowering their saturated fat intake.", impact: "LOW. Saturated fat consumption and this specific genetic variant are only a small component of BMI. Other healthy life choices are important for maintaining a healthy weight.", frequency: "58.20%", references: "24108135, 26210798, 19901143").save!
HelixInfo.new(gene: "FADS2", variant: "rs174537", a1: "T", a2: "T", trait: "Omega-3 metabolism", insight: "TT individuals are more likely to have lower EPA (eicosapentanoic acid) in the blood, a type of Omega-3 fatty acids.", recommend: "These individuals should consider adding more omega-3 fatty acids to their diet, if they don't already have a diet high in omega 3s. Cold water fish are a good source.", impact: "LOW. The effect of genetics is much lower than the effect of diet.", frequency: "9%", references: "19148276").save!
HelixInfo.new(gene: "FADS2", variant: "rs174537", a1: "T", a2: "G", trait: "Omega-3 metabolism", insight: "TG individuals are more likely to have normal levels of EPA in the blood, a type of Omega-3 fatty acids.", recommend: "Omega 3 fatty acids are part of a healthy diet. Although you aren't at risk of having low Omega 3s due to genetics, you should make sure you are eating foods that contain these important fatty acids.", impact: "LOW. The effect of genetics is much lower than the effect of diet.", frequency: "42%", references: "19148276").save!
HelixInfo.new(gene: "FADS2", variant: "rs174537", a1: "G", a2: "G", trait: "Omega-3 metabolism", insight: "GG individuals are likely to have normal levels of EPA in the blood, a type of Omega-3 fatty acids.", recommend: "Omega 3 fatty acids are part of a healthy diet. Although you aren't at risk of having low Omega 3s due to genetics, you should make sure you are eating foods that contain these important fatty acids.", impact: "LOW. The effect of genetics is much lower than the effect of diet.", frequency: "49%", references: "19148276").save!
HelixInfo.new(gene: "MUC1", variant: "rs4072037", a1: "C", a2: "C", trait: "Magnesium metabolism", insight: "CC individuals are more likely to have lower serum magnesium levels", recommend: "Consider adding foods to your diet that are high in magnesium.", impact: "LOW. The effects of genetics is much lower than the effect of diet.", frequency: "21%", references: "20700443").save!
HelixInfo.new(gene: "MUC1", variant: "rs4072037", a1: "C", a2: "T", trait: "Magnesium metabolism", insight: "CT individuals likely to have typical magnesium levels", recommend: "Genetics may not be a big factor in your magnesium levels, but it is still important to get sufficient amounts through your diet", impact: "LOW. The effects of genetics is much lower than the effect of diet.", frequency: "50%", references: "20700443").save!
HelixInfo.new(gene: "MUC1", variant: "rs4072037", a1: "T", a2: "T", trait: "Magnesium metabolism", insight: "TT individuals likely to have typical magnesium levels", recommend: "Genetics may not be a big factor in your magnesium levels, but it is still important to get sufficient amounts through your diet", impact: "LOW. The effects of genetics is much lower than the effect of diet.", frequency: "29%", references: "20700443").save!
HelixInfo.new(gene: "TMPRSS6", variant: "rs855791", a1: "G", a2: "G", trait: "Iron metabolism", insight: "GG individuals likely to have typical iron levels", recommend: "The only way to know if your iron levels are normal is a blood test. And if your diet is low in iron, you may still have lower levels.", impact: "LOW. The effect of genetics is much lower than the effect of diet.", frequency: "36%", references: "19880490, 19820699, 19084217, 21208937").save!
HelixInfo.new(gene: "TMPRSS6", variant: "rs855791", a1: "G", a2: "A", trait: "Iron metabolism", insight: "GA individuals likely to have typical iron levels", recommend: "The only way to know if your iron levels are normal is a blood test. And if your diet is low in iron, you may still have lower levels.", impact: "LOW. The effect of genetics is much lower than the effect of diet.", frequency: "48%", references: "19880490, 19820699, 19084217, 21208937").save!
HelixInfo.new(gene: "TMPRSS6", variant: "rs855791", a1: "A", a2: "A", trait: "Iron metabolism", insight: "AA individuals are more likely to have lower iron levels", recommend: "Iron is important for a number of processes in the body and having a diet with enough iron is important. Since your genetics indicate lower levels, make sure to get enough iron through the foods you are eating.", impact: "LOW. The effect of genetics is much lower than the effect of diet.", frequency: "16%", references: "19880490, 19820699, 19084217, 21208937").save!
HelixInfo.new(gene: "FUT2", variant: "rs602662", a1: "A", a2: "A", trait: "B12 metabolism", insight: "AA individuals likely to have typical B12 levels", recommend: "Your genetics suggest that your B12 are more likely to be typical, but if you aren't maintaining a balanced diet, you may still fall short. Make sure to have red meat, dairy or eggs are part of your diet.", impact: "LOW. The effect of genetics is much lower than the effect of diet.", frequency: "10%", references: "19303062, 19744961").save!
HelixInfo.new(gene: "FUT2", variant: "rs602662", a1: "A", a2: "G", trait: "B12 metabolism", insight: "AG individuals likely to have typical B12 levels", recommend: "Your genetics suggest that your B12 are more likely to be typical, but if you aren't maintaining a balanced diet, you may still fall short. Make sure to have red meat, dairy or eggs are part of your diet.", impact: "LOW. The effect of genetics is much lower than the effect of diet.", frequency: "43%", references: "19303062, 19744961").save!
HelixInfo.new(gene: "FUT2", variant: "rs602662", a1: "G", a2: "G", trait: "B12 metabolism", insight: "GG individuals are more likely to have lower B12 levels", recommend: "Even though you may have lower B12 levels, B12 can be found in lots of foods. Focus on foods rich in B12 like cereals, red meat, dairy or eggs.", impact: "LOW. The effect of genetics is much lower than the effect of diet.", frequency: "45%", references: "19303062, 19744961").save!
HelixInfo.new(gene: "ALPL", variant: "rs4654748", a1: "C", a2: "C", trait: "B6 metabolism", insight: "CC individuals may have lower B6 levels due to genetics.", recommend: "The best source of B6 is organ meats, but for those of you who don't like the sound of that, many cereals are already fortified with B6. Other great sources are starchy vegetables like potatoes.", impact: "LOW. The effect of genetics is much lower than the effect of diet.", frequency: "39%", references: "19744961, 19303062").save!
HelixInfo.new(gene: "ALPL", variant: "rs4654748", a1: "T", a2: "C", trait: "B6 metabolism", insight: "B6 levels are not expected to be affected by this variant in TC individuals.", recommend: "You may not have the genetic variant that may give you lower B6 levels, but your levels might be low if you aren't eating a balanced diet.", impact: "LOW. The effect of genetics is much lower than the effect of diet.", frequency: "47%", references: "19744961, 19303062").save!
HelixInfo.new(gene: "ALPL", variant: "rs4654748", a1: "T", a2: "T", trait: "B6 metabolism", insight: "B6 levels are not expected to be affected by this variant in TT individuals.", recommend: "You may not have the genetic variant that may give you lower B6 levels, but your levels might be low if you aren't eating a balanced diet.", impact: "LOW. The effect of genetics is much lower than the effect of diet.", frequency: "14%", references: "19744961, 19303062").save!
HelixInfo.new(gene: "CYP1A1/2", variant: "rs762551", a1: "A", a2: "A", trait: "Caffeine", insight: "AA individuals are considered fast metabolizers of caffeine", recommend: "Individuals are likely able to drink caffeine as normal.", impact: "HIGH. Genetics plays a large role in metabolism. However, personal preferences and environment may also play a large role. For example, you may be a slow metabolizer of caffeine but drink a few cups of coffee per day. This might mean that the effect of caffee on you is different than a slow metabolizer who never drinks caffeine.", frequency: "40%", references: "25288136, 21357676, 21490707, 21876539").save!
HelixInfo.new(gene: "CYP1A1/2", variant: "rs762551", a1: "A", a2: "C", trait: "Caffeine", insight: "AC individuals are considered slow metabolizers of caffeine", recommend: "You may want to drink less caffeine as you will experience the effects for longer.", impact: "HIGH. Genetics plays a large role in metabolism. However, personal preferences and environment may also play a large role. For example, you may be a slow metabolizer of caffeine but drink a few cups of coffee per day. This might mean that the effect of caffee on you is different than a slow metabolizer who never drinks caffeine.", frequency: "46%", references: "25288136, 21357676, 21490707, 21876539").save!
HelixInfo.new(gene: "CYP1A1/2", variant: "rs762551", a1: "C", a2: "C", trait: "Caffeine", insight: "CC individuals are considered slow metabolizers of caffeine", recommend: "You may want to drink less caffeine as you will experience the effects for longer.", impact: "HIGH. Genetics plays a large role in metabolism. However, personal preferences and environment may also play a large role. For example, you may be a slow metabolizer of caffeine but drink a few cups of coffee per day. This might mean that the effect of caffee on you is different than a slow metabolizer who never drinks caffeine.", frequency: "13%", references: "25288136, 21357676, 21490707, 21876539").save!
HelixInfo.new(gene: "Polygenic score---", variant: "", a1: "", a2: "", trait: "BMI", insight: "Individuals are prediposed to increased BMI", recommend: "Recommend healthy behaviors.", impact: "LOW. The effects of genetics are lower than environment.", frequency: "20%", references: "20935630").save!
HelixInfo.new(gene: "Polygenic score---", variant: "", a1: "", a2: "", trait: "BMI", insight: "Individuals are predisposed to typical BMI", recommend: "Recommend healthy behaviors.", impact: "LOW. The effects of genetics are lower than environment.", frequency: "60%", references: "20935630").save!
HelixInfo.new(gene: "Polygenic score---", variant: "", a1: "", a2: "", trait: "BMI", insight: "Individuals are prediposed to lower BMI", recommend: "Recommend healthy behaviors.", impact: "LOW. The effects of genetics are lower than environment.", frequency: "20%", references: "20935630").save!
HelixInfo.new(gene: "Polygenic score---", variant: "", a1: "", a2: "", trait: "Sugary beverage consumption + BMI", insight: "Individuals are predisposed to greater weight gain when consuming at least one sugary beverage a day", recommend: "Avoid sugar-sweetened beverages. Decreasing from >1 a day to less than 1 per day is enough to lower risk.", impact: "LOW. The effects of genetics are lower than environment.", frequency: "20%", references: "22998338").save!
HelixInfo.new(gene: "Polygenic score---", variant: "", a1: "", a2: "", trait: "Sugary beverage consumption + BMI", insight: "Individuals are predisposed to typical weight gain when consuming at least one sugary beverage a day", recommend: "Everyone should avoid sugary beverages.", impact: "LOW. The effects of genetics are lower than environment.", frequency: "80%", references: "22998338").save!
HelixInfo.new(gene: "Polygenic Score---", variant: "", a1: "", a2: "", trait: "Blood Glucose", insight: "Top 20% of individuals may have higher blood glucose levels.", recommend: "There are lots of steps to take including staying hydrated, eating low-glycemic foods, and replacing carbs with food high in fiber.", impact: "LOW. The effect of genetics is much lower than the effect of diet.", frequency: "77%", references: "20081858").save!
HelixInfo.new(gene: "Polygenic Score---", variant: "", a1: "", a2: "", trait: "Blood Glucose", insight: "The middle 60% of individuals may have typical blood glucose levels.", recommend: "Recommend healthy behaviors.", impact: "LOW. The effect of genetics is much lower than the effect of diet.", frequency: "19%", references: "20081858").save!
HelixInfo.new(gene: "Polygenic Score---", variant: "", a1: "", a2: "", trait: "Blood Glucose", insight: "The botton 20% of individuals may have lower blood glucose levels", recommend: "Recommend healthy behaviors.", impact: "LOW. The effect of genetics is much lower than the effect of diet.", frequency: "1.20%", references: "20081858").save!
HelixInfo.new(gene: "GC", variant: "rs2282679", a1: "G", a2: "G", trait: "Vitamin D", insight: "GG individuals may have lower vitamin D levels", recommend: "Go for a 10 minute walk outside during your lunch break. Getting small amounts of sun can improve vitamin D levels", impact: "LOW. The effect of genetics is much lower than the effect of diet.", frequency: "4%", references: "20541252, 26038244, 24587115").save!
HelixInfo.new(gene: "GC", variant: "rs2282679", a1: "T", a2: "G", trait: "Vitamin D", insight: "TG individuals are more likely to have typical Vitamin D levels", recommend: "Keep doing what you're doing. Unless you aren't eating foods that are good sources of Vitamin D", impact: "LOW. The effect of genetics is much lower than the effect of diet.", frequency: "32%", references: "20541252, 26038244, 24587115").save!
HelixInfo.new(gene: "GC", variant: "rs2282679", a1: "T", a2: "T", trait: "Vitamin D", insight: "TT individuals are more likely to have typical Vitamin D levels", recommend: "Keep doing what you're doing. Unless you aren't eating foods that are good sources of Vitamin D", impact: "LOW. The effect of genetics is much lower than the effect of diet.", frequency: "64%", references: "20541252, 26038244, 24587115").save!
HelixInfo.new(gene: "HLA", variant: "rs2187668", a1: "T", a2: "T", trait: "Gluten Tolerance", insight: "TT individuals are more likely to have a gluten intolerance.", recommend: "If you experience pain, bloating, or diarrhea after eating gluten, avoiding gluten in your diet should reduce your symptoms", impact: "HIGH. Environment plays a small role. We also don't fully understand how genetics affects when someone will present with gluten intolerance", frequency: "0.50%", references: "18509540, 25894500, 26258845, PMC4596973").save!
HelixInfo.new(gene: "HLA", variant: "rs2187668", a1: "T", a2: "C", trait: "Gluten Tolerance", insight: "TC individuals are more likely to have a gluten intolerance", recommend: "If you experience pain, bloating, or diarrhea after eating gluten, avoiding gluten in your diet should reduce your symptoms", impact: "HIGH. Environment plays a small role. We also don't fully understand how genetics affects when someone will present with gluten intolerance", frequency: "13%", references: "18509540, 25894500, 26258845, PMC4596973").save!
HelixInfo.new(gene: "HLA", variant: "rs2187668", a1: "C", a2: "C", trait: "Gluten Tolerance", insight: "CC are unlikely to have a gluten intolerance", recommend: "Continue eating gluten containing foods.", impact: "HIGH. Environment plays a small role. We also don't fully understand how genetics affects when someone will present with gluten intolerance", frequency: "86%", references: "18509540, 25894500, 26258845, PMC4596973").save!
HelixInfo.new(gene: "FTO", variant: "rs9939609", a1: "A", a2: "A", trait: "Physical Activity effect on weight", insight: "AA individuals who are physically active have a lower risk of increased BMI.", recommend: "Being physically active, even just walking, may help you reduce your genetic risk for gaining more weight.", impact: "LOW. The role of genetics in weight loss is much lower than the effect of increased exercise and decreased calorie intake. In addition, the interaction between genetics and physical activity it low.", frequency: "12%", references: "22069379, 21179003").save!
HelixInfo.new(gene: "FTO", variant: "rs9939609", a1: "A", a2: "T", trait: "Physical Activity effect on weight", insight: "AT individuals who are physically active have a lower risk of increased BMI.", recommend: "Being physically active, even just walking, may help you reduce your genetic risk for gaining more weight.", impact: "LOW. The role of genetics in weight loss is much lower than the effect of increased exercise and decreased calorie intake. In addition, the interaction between genetics and physical activity it low.", frequency: "45%", references: "22069379, 21179003").save!
HelixInfo.new(gene: "FTO", variant: "rs9939609", a1: "T", a2: "T", trait: "Physical Activity effect on weight", insight: "Physical activity in TT individuals does not have the same effect.", recommend: "According to the one genetic variant we looked at, physical activity won't help you as much as it helps others. But keep in mind that physical activity is important for a number of reasons. Maybe just make sure you are eating healthy if you are looking to lose weight.", impact: "LOW. The role of genetics in weight loss is much lower than the effect of increased exercise and decreased calorie intake. In addition, the interaction between genetics and physical activity it low.", frequency: "44%", references: "22069379, 21179003").save!
HelixInfo.new(gene: "TAS2R38", variant: "rs10246939", a1: "C", a2: "C", trait: "Bitter Taste", insight: "CC individuals are bitter tasters.", recommend: "Don't force yourself to eat brussel sprouts and broccoli if you don't like them. There are tons of other delicious vegetables out there.", impact: "LOW. While the bitter taste gene has been studied quite a bit, and the trait is well known, the genetics aren't as clear cut. You can still train yourself to like bitter tastes, even if they may be more intense to some than others.", frequency: "27%", references: "22132133").save!
HelixInfo.new(gene: "TAS2R38", variant: "rs10246939", a1: "C", a2: "T", trait: "Bitter Taste", insight: "CT individuals are inbetween bitter tasters.", recommend: "Don't force yourself to eat brussel sprouts and broccoli if you don't like them. There are tons of other delicious vegetables out there.", impact: "LOW. While the bitter taste gene has been studied quite a bit, and the trait is well known, the genetics aren't as clear cut. You can still train yourself to like bitter tastes, even if they may be more intense to some than others.", frequency: "49%", references: "22132133").save!
HelixInfo.new(gene: "TAS2R38", variant: "rs10246939", a1: "T", a2: "T", trait: "Bitter Taste", insight: "TT individuals are non-tasters.", recommend: "Looks like you can't blame genetics when you pass on the brussel sprouts next time. But I won't tell anyone if you don't.", impact: "LOW. While the bitter taste gene has been studied quite a bit, and the trait is well known, the genetics aren't as clear cut. You can still train yourself to like bitter tastes, even if they may be more intense to some than others.", frequency: "23%", references: "22132133").save!
HelixInfo.new(gene: "SLC2A2", variant: "rs5400", a1: "A", a2: "A", trait: "Sweet Tooth", insight: "AA individuals are more likely to have a sweet tooth.", recommend: "You may have the sweet tooth and it is important to keep in mind that you may eat more sugar than others. Try to look out for sugars in the foods you eat to make sure you aren't over doing it.", impact: "LOW. Genetics is just a small component of your personal preferences.", frequency: "4%", references: "18349384").save!
HelixInfo.new(gene: "SLC2A2", variant: "rs5400", a1: "A", a2: "G", trait: "Sweet Tooth", insight: "AG individuals are more likely to have a sweet tooth.", recommend: "You may have the sweet tooth and it is important to keep in mind that you may eat more sugar than others. Try to look out for sugars in the foods you eat to make sure you aren't over doing it.", impact: "LOW. Genetics is just a small component of your personal preferences.", frequency: "33%", references: "18349384").save!
HelixInfo.new(gene: "SLC2A2", variant: "rs5400", a1: "G", a2: "G", trait: "Sweet Tooth", insight: "GG individuals are not likely to have a sweet tooth.", recommend: "Your genes may not give you a sweet tooth, but you still may enjoy desserts.", impact: "LOW. Genetics is just a small component of your personal preferences.", frequency: "61%", references: "18349384").save!
HelixInfo.new(gene: "COL1A1", variant: "rs1800012", a1: "A", a2: "A", trait: "ACL Tear", insight: "AA individuals are more likely to be protected from ACL injury", recommend: "While your genetics may provide some protection from ACL injury, how you train can put you at greater risk.", impact: "LOW. Training and the activities you engage in play a much larger role in your injury risk than genetics.", frequency: "1%", references: "18669982, 19193663").save!
HelixInfo.new(gene: "COL1A1", variant: "rs1800012", a1: "C", a2: "A", trait: "ACL Tear", insight: "CA individuals are likely to have average risk for ACL injury", recommend: "If you are currently putting lots of strain on your knees (like playing soccer, football, or backetball), you may want to focus on strengthing your quadriceps.", impact: "LOW. Training and the activities you engage in play a much larger role in your injury risk than genetics.", frequency: "16%", references: "18669982, 19193663").save!
HelixInfo.new(gene: "COL1A1", variant: "rs1800012", a1: "C", a2: "C", trait: "ACL Tear", insight: "CC individuals are likely to have average risk for ACL injury", recommend: "If you are currently putting lots of strain on your knees (like playing soccer, football, or backetball), you may want to focus on strengthing your quadriceps.", impact: "LOW. Training and the activities you engage in play a much larger role in your injury risk than genetics.", frequency: "83%", references: "18669982, 19193663").save!
HelixInfo.new(gene: "COL5A1", variant: "rs12722", a1: "C", a2: "C", trait: "Achilles Tendinopathy", insight: "CC indivduals are not likely to be at increased risk for Achilles tendon injury", recommend: "While you don't have an increased risk for Achilles injury based on genetics, over training and over stressing your Achilles may still put you at risk for injury.", impact: "LOW. Training and the activities you engage in play a much larger role in your injury risk than genetics.", frequency: "42%", references: "18443036, 19042922").save!
HelixInfo.new(gene: "COL5A1", variant: "rs12722", a1: "C", a2: "T", trait: "Achilles Tendinopathy", insight: "CT individuals may be at increased risk for Achilles tendon injury", recommend: "If you are currently putting lots of strain on your Achilles Tendon or have started training for the first time, you should incorporate some stretching to prodect your Achilles. Heel raises and calf stretches are a good start.", impact: "LOW. Training and the activities you engage in play a much larger role in your injury risk than genetics.", frequency: "46%", references: "18443036, 19042922").save!
HelixInfo.new(gene: "COL5A1", variant: "rs12722", a1: "T", a2: "T", trait: "Achilles Tendinopathy", insight: "TT individuals may be at increased risk for Achilles tendon injury", recommend: "If you are currently putting lots of strain on your Achilles Tendon or have started training for the first time, you should incorporate some stretching to prodect your Achilles. Heel raises and calf stretches are a good start.", impact: "LOW. Training and the activities you engage in play a much larger role in your injury risk than genetics.", frequency: "12%", references: "18443036, 19042922").save!
HelixInfo.new(gene: "Polygenic score---", variant: "", a1: "", a2: "", trait: "Stress Fracture", insight: "The top 20% of people are predisposed to increased risk for stress fracture.", recommend: "Cross-training is the best way to prevent stress fractures. By mixing up the types of exercises you are doing, the less you are likely to overdo it.", impact: "LOW. Training and the activities you engage in play a much larger role in your injury risk than genetics.", frequency: "1.20%", references: "22504420").save!
HelixInfo.new(gene: "Polygenic score---", variant: "", a1: "", a2: "", trait: "Stress Fracture", insight: "Middle 60% of people are predisposed to typical risk of stress fracture.", recommend: "Cross-training is the best way to prevent stress fractures. By mixing up the types of exercises you are doing, the less you are likely to overdo it.", impact: "LOW. Training and the activities you engage in play a much larger role in your injury risk than genetics.", frequency: "20%", references: "22504420").save!
HelixInfo.new(gene: "Polygenic score---", variant: "", a1: "", a2: "", trait: "Stress Fracture", insight: "Bottom 20% of people are predisposed to lower risk of stress fracture.", recommend: "Just because your genetics don't increase your risk, doesn't mean you are protected from injury. Make sure to set incremental goals and build rest days into your training, especially when running.", impact: "LOW. Training and the activities you engage in play a much larger role in your injury risk than genetics.", frequency: "77%", references: "22504420").save!
HelixInfo.new(gene: "ACTN3", variant: "rs1815739", a1: "C", a2: "C", trait: "Fast vs Slow Twitch", insight: "CC individuals have more fast twitch muscles which may be better suited for power-requiring activities", recommend: "Its important to remember that doing what you like is much more important than doing what your genetics suggests you might be better suited for. But if you are looking for suggestions, try short, high intensity, anaerobic exercises.", impact: "LOW. Training and the activities you engage in play a much larger role in your athletic performance.", frequency: "36%", references: "12879365").save!
HelixInfo.new(gene: "ACTN3", variant: "rs1815739", a1: "C", a2: "T", trait: "Fast vs Slow Twitch", insight: "CT individuals have a mix of fast and slow muscles and may be suited for both power and endurance activities", recommend: "Its important to remember that doing what you like is much more important than doing what your genetics suggests you might be better suited for. Lucky for you, you can dabble in the all.", impact: "LOW. Training and the activities you engage in play a much larger role in your athletic performance.", frequency: "48%", references: "12879365").save!
HelixInfo.new(gene: "ACTN3", variant: "rs1815739", a1: "T", a2: "T", trait: "Fast vs Slow Twitch", insight: "TT individuals have more slow twitch muscles which may be better suited for endurance activities", recommend: "Its important to remember that doing what you like is much more important than doing what your genetics suggests you might be better suited for. If you are looking for suggestions, aerobic, endurance-based activities might give you an edge.", impact: "LOW. Training and the activities you engage in play a much larger role in your athletic performance.", frequency: "16%", references: "12879365").save!
HelixInfo.new(gene: "TRPV4", variant: "rs3742030", a1: "A", a2: "A", trait: "Hydration", insight: "AA individuals are more likely to have low sodium levels due to your DNA", recommend: "If you are exercising and sweating a lot, consider adding an electrolyte containing sports drink to your workout regimine. Keep in mind that too much salt can be bad for your health, and if you are already getting a diet with enough salt, you have little to worry about.", impact: "LOW. Diet is a bigger contributor to sodium levels than genetics.", frequency: "0.15%", references: "19666518").save!
HelixInfo.new(gene: "TRPV4", variant: "rs3742030", a1: "A", a2: "G", trait: "Hydration", insight: "AG individuals are more likely to have low sodium levels due to your DNA", recommend: "If you are exercising and sweating a lot, consider adding an electrolyte containing sports drink to your workout regimine. Keep in mind that too much salt can be bad for your health, and if you are already getting a diet with enough salt, you have little to worry about.", impact: "LOW. Diet is a bigger contributor to sodium levels than genetics.", frequency: "7.60%", references: "19666518").save!
HelixInfo.new(gene: "TRPV4", variant: "rs3742030", a1: "G", a2: "G", trait: "Hydration", insight: "GG individuals are less likely to have low sodium levels due to your DNA", recommend: "Genetics is only a piece of your sodium level, so you may be low in sodium for other reasons like diet.", impact: "LOW. Diet is a bigger contributor to sodium levels than genetics.", frequency: "90%", references: "19666518").save!
HelixInfo.new(gene: "SHBG", variant: "rs12150660", a1: "T", a2: "T", trait: "Testosterone Levels", insight: "TT individuals are predisposed to having higher testosterone levels", recommend: "", impact: "MED. Known genetic factors explain a small amount of the variance", frequency: "0.90%", references: "21998597").save!
HelixInfo.new(gene: "SHBG", variant: "rs12150660", a1: "T", a2: "G", trait: "Testosterone Levels", insight: "TG individuals are predisposed to having higher testosterone levels", recommend: "", impact: "MED. Known genetic factors explain a small amount of the variance", frequency: "17%", references: "21998597").save!
HelixInfo.new(gene: "SHBG", variant: "rs12150660", a1: "G", a2: "G", trait: "Testosterone Levels", insight: "Testosterone levels are not affected in GG individuals", recommend: "", impact: "MED. Known genetic factors explain a small amount of the variance", frequency: "82%", references: "21998597").save!
HelixInfo.new(gene: "SHBG", variant: "rs6258", a1: "T", a2: "T", trait: "Testosterone Levels", insight: "TT individuals are predisposed to having lower testosterone levels", recommend: "", impact: "MED. Known genetic factors explain a small amount of the variance", frequency: "<0.1%", references: "21998597").save!
HelixInfo.new(gene: "SHBG", variant: "rs6258", a1: "T", a2: "A/C", trait: "Testosterone Levels", insight: "T/AC individuals are predisposed to having lower testosterone levels", recommend: "", impact: "MED. Known genetic factors explain a small amount of the variance", frequency: "0.30%", references: "21998597").save!
HelixInfo.new(gene: "SHBG", variant: "rs6258", a1: "A/C", a2: "A/C", trait: "Testosterone Levels", insight: "Testosterone levels are not affected in AC/AC individuals", recommend: "", impact: "MED. Known genetic factors explain a small amount of the variance", frequency: "99.60%", references: "21998597").save!
HelixInfo.new(gene: "FADS2", variant: "rs1535", a1: "G", a2: "G", trait: "Omega 3/Asthma", insight: "GG individuals are predisposed to having lower EPA levels.", recommend: "In one preliminary study, babies born to women who had the low levels of EPA were more likely to have asthma. This increased risk was reduced if the women increased the amount of n-3 LCPUFAs in their diet. Women in their third trimester should consider increasing the amount of omega fatty acids in their diet.", impact: "LOW. Genetic factors are less impactful than dietary factors.", frequency: "10%", references: "28029926").save!
HelixInfo.new(gene: "FADS2", variant: "rs1535", a1: "G", a2: "A", trait: "Omega 3/Asthma", insight: "GA individuals are not predisposed to having lower EPA levels.", recommend: "In one preliminary study, babies born to women who had the low levels of EPA were more likely to have asthma. This increased risk was reduced if the women increased the amount of n-3 LCPUFAs in their diet. While your gene variant isn't associated with lower EPA levels, you may have lower EPA levels if you aren't getting enough n-3 LCPUFAs in your diet.", impact: "LOW. Genetic factors are less impactful than dietary factors.", frequency: "44%", references: "28029926").save!
HelixInfo.new(gene: "FADS2", variant: "rs1535", a1: "A", a2: "A", trait: "Omega 3/Asthma", insight: "AA individuals are not predisposed to having lower EPA levels.", recommend: "In one preliminary study, babies born to women who had the low levels of EPA were more likely to have asthma. This increased risk was reduced if the women increased the amount of n-3 LCPUFAs in their diet. While your gene variant isn't associated with lower EPA levels, you may have lower EPA levels if you aren't getting enough n-3 LCPUFAs in your diet.", impact: "LOW. Genetic factors are less impactful than dietary factors.", frequency: "46%", references: "28029926").save!
HelixInfo.new(gene: "CDKAL1", variant: "rs7754840", a1: "C", a2: "C", trait: "Gestational Diabetes", insight: "CC individuals are predisposed to a slightly higher risk for gestational diabetes.", recommend: "While there is nothing you can do to prevent gestational diabetes, being aware of increased risk can help you be prepared.", impact: "LOW. Genetic factors are less impactful than dietary and other risk factors.", frequency: "16%", references: "22233651").save!
HelixInfo.new(gene: "CDKAL1", variant: "rs7754840", a1: "C", a2: "G", trait: "Gestational Diabetes", insight: "CG individuals are predisposed to a slightly higher risk for gestational diabetes.", recommend: "While there is nothing you can do to prevent gestational diabetes, being aware of increased risk can help you be prepared.", impact: "LOW. Genetic factors are less impactful than dietary and other risk factors.", frequency: "48%", references: "22233651").save!
HelixInfo.new(gene: "CDKAL1", variant: "rs7754840", a1: "G", a2: "G", trait: "Gestational Diabetes", insight: "GG individuals are not predisposed to a higher risk of gestational diabetes", recommend: "While there is nothing you can do to prevent gestational diabetes, being aware of increased risk can help you be prepared.", impact: "LOW. Genetic factors are less impactful than dietary and other risk factors.", frequency: "35%", references: "22233651").save!
HelixInfo.new(gene: "MTHFR", variant: "rs1801133", a1: "A", a2: "A", trait: "Folate", insight: "AA individuals are predisposed to lower folate levels", recommend: "Consider adding folic acid fortified foods to your diet and making sure you are getting the recommended amount of folate during pregnancy.", impact: "LOW. Genetic factors are less impactful than dietary factors.", frequency: "6%", references: "22230384, 17436239, 14985224").save!
HelixInfo.new(gene: "MTHFR", variant: "rs1801133", a1: "A", a2: "G", trait: "Folate", insight: "AG individuals are predisposed to lower folate levels", recommend: "Consider adding folic acid fortified foods to your diet and making sure you are getting the recommended amount of folate during pregnancy.", impact: "LOW. Genetic factors are less impactful than dietary factors.", frequency: "37%", references: "22230384, 17436239, 14985224").save!
HelixInfo.new(gene: "MTHFR", variant: "rs1801133", a1: "G", a2: "G", trait: "Folate", insight: "GG individuals are not predisposed to lower folate levels.", recommend: "Folate is important for every pregancy, and while your genetics don't indicate an increased need, you still want to make sure you are getting adequate folate intake.", impact: "LOW. Genetic factors are less impactful than dietary factors.", frequency: "57%", references: "22230384, 17436239, 14985224").save!
HelixInfo.new(gene: "ALDH2", variant: "rs671", a1: "A", a2: "A", trait: "Alcohol Flush", insight: "AA individuals are likely to be sensitive to alcohol.", recommend: "Likely sensitive to alcohol. Recommend drinking less or stopping completely.", impact: "HIGH. Environment plays a small role, and the genetics might not be perfectly correlated with the trait.", frequency: "0.12%", references: "10441588, 24277619, 26825972").save!
HelixInfo.new(gene: "ALDH2", variant: "rs671", a1: "A", a2: "G", trait: "Alcohol Flush", insight: "AG individuals are likely to be sensitive to alcohol.", recommend: "Likely sensitive to alcohol. Recommend drinking less or stopping completely.", impact: "HIGH. Environment plays a small role, and the genetics might not be perfectly correlated with the trait.", frequency: "6.70%", references: "10441588, 24277619, 26825972").save!
HelixInfo.new(gene: "ALDH2", variant: "rs671", a1: "G", a2: "G", trait: "Alcohol Flush", insight: "GG individuals are not likely to be sensitive to alcohol based on their genetics.", recommend: "Likely not sensitive to alcohol. Drink in moderation.", impact: "HIGH. Environment plays a small role, and the genetics might not be perfectly correlated with the trait.", frequency: "92%", references: "10441588, 24277619, 26825972").save!
HelixInfo.new(gene: "Polygenic Score---", variant: "", a1: "", a2: "", trait: "Bone mineral density", insight: "Individuals in the top 20% are predisposed to lower bone mineral density", recommend: "There are a number of steps you can take to increase your bone density. The first is with diet. Increasing the amount of Vitamin D and calcium in your diet by consuming dairy and dark leafy vegetables will help. The second is exercise. Weight bearing exercises are key for building and maintaining strong bones. Lastly, reducing caffeine and alcohol intake can help as well.", impact: "LOW. The effect of genetics is smaller than that of diet.", frequency: "20%", references: "22504420").save!
HelixInfo.new(gene: "Polygenic Score---", variant: "", a1: "", a2: "", trait: "Bone mineral density", insight: "Individuals in the middle 60% are predisposed to typical bone mineral density", recommend: "Just because you are predisposed to typical bone density doesn't mean you are in the clear. Getting sufficient Vitamin D and Calcium as well as preforming weight bearing exercises is a good start.", impact: "LOW. The effect of genetics is smaller than that of diet.", frequency: "60%", references: "22504420").save!
HelixInfo.new(gene: "Polygenic Score---", variant: "", a1: "", a2: "", trait: "Bone mineral density", insight: "Individuals in the bottom 20% are predisposed to higher bone mineral density", recommend: "Just because you are predisposed to high bone density doesn't mean you are in the clear. Getting sufficient Vitamin D and Calcium as well as preforming weight bearing exercises is a good start.", impact: "LOW. The effect of genetics is smaller than that of diet.", frequency: "20%", references: "22504420").save!
HelixInfo.new(gene: "Polygenic score---", variant: "", a1: "", a2: "", trait: "Endurance vs Power", insight: "Individuals are more likely to excel at endurance sports", recommend: "Having the same genes as many endurance athletes doesn't mean you will be able to run a 2 hour marathon, but it does mean that you might excel at activities that required sustained aerobic performance.", impact: "LOW. The effect of genetics is much lower than the effect of training.", frequency: "20%", references: "19653005").save!
HelixInfo.new(gene: "Polygenic score---", variant: "", a1: "", a2: "", trait: "Endurance vs Power", insight: "Individuals are less likely to excel at endurance sports", recommend: "Just because you don't share genes with endurance athletes doesn't mean you should give up endurance activities. Continue doing what you love, but if you are looking for a new activity, try some that require short bursts of power.", impact: "LOW. The effect of genetics is much lower than the effect of training.", frequency: "80%", references: "19653005").save!
HelixInfo.new(gene: "Polygenic Score---", variant: "", a1: "", a2: "", trait: "Triglycerides", insight: "Individuals in the top 20% may be predisposed to higher triglycerides", recommend: "Get more exercise and reduce carbohydrate intake is recommended to lower triglyceride levels", impact: "LOW. The effect of genetics is much lower than the effect of diet.", frequency: "4.80%", references: "20686565, 24097068").save!
HelixInfo.new(gene: "Polygenic Score---", variant: "", a1: "", a2: "", trait: "Triglycerides", insight: "Individuals in the middle 60% may be predisposed to typical triglycerides", recommend: "Recommend healthy behaviors.", impact: "LOW. The effect of genetics is much lower than the effect of diet.", frequency: "34%", references: "20686565, 24097068").save!
HelixInfo.new(gene: "Polygenic Score---", variant: "", a1: "", a2: "", trait: "Triglycerides", insight: "Individuals in the bottom 20% may be predisposed to lower triglycerides", recommend: "Recommend healthy behaviors", impact: "LOW. The effect of genetics is much lower than the effect of diet.", frequency: "59%", references: "20686565, 24097068").save!
HelixInfo.new(gene: "Polygenic Score---", variant: "", a1: "", a2: "", trait: "HDL", insight: "Individuals in the top 20% may be predisposed to higher HDL", recommend: "Recommend healthy behaviors.", impact: "LOW. The effect of genetics is much lower than the effect of diet.", frequency: "8.40%", references: "20686565, 24097068").save!
HelixInfo.new(gene: "Polygenic Score---", variant: "", a1: "", a2: "", trait: "HDL", insight: "Individuals in the middle 60% may be predisposed to typical HDL", recommend: "Stop smoking, get more exercise, and maintain a healthy weight. All these have been shown to help raise HDL levels", impact: "LOW. The effect of genetics is much lower than the effect of diet.", frequency: "41%", references: "20686565, 24097068").save!
HelixInfo.new(gene: "Polygenic Score---", variant: "", a1: "", a2: "", trait: "HDL", insight: "Individuals in the bottom 20% may be predisposed to lower HDL", recommend: "Stop smoking, get more exercise, and maintain a healthy weight. All these have been shown to help raise HDL levels", impact: "LOW. The effect of genetics is much lower than the effect of diet.", frequency: "50%", references: "20686565, 24097068").save!
HelixInfo.new(gene: "Polygenic Score---", variant: "", a1: "", a2: "", trait: "LDL", insight: "Individuals in the top 20% may be predisposed to higher LDL", recommend: "Recommend exercise, diets low in saturated fats and simple carbs, and stop smoking.", impact: "LOW. The effect of genetics is much lower than the effect of diet.", frequency: "17%", references: "20686565, 24097068").save!
HelixInfo.new(gene: "Polygenic Score---", variant: "", a1: "", a2: "", trait: "LDL", insight: "Individuals in the middle 60% may be predisposed to typical LDL", recommend: "Recommend healthy behaviors.", impact: "LOW. The effect of genetics is much lower than the effect of diet.", frequency: "48%", references: "20686565, 24097068").save!
HelixInfo.new(gene: "Polygenic Score---", variant: "", a1: "", a2: "", trait: "LDL", insight: "Individuals in the bottom 20% may be predisposed to lower LDL", recommend: "Recommend healthy behaviors.", impact: "LOW. The effect of genetics is much lower than the effect of diet.", frequency: "34%", references: "20686565, 24097068").save!
HelixInfo.new(gene: "RGS16", variant: "rs516134", a1: "C", a2: "C", trait: "Morningness", insight: "CC individuals are more likely to identify as a morning person", recommend: "", impact: "LOW. The effect of genetics is much lower than the effect of environment.", frequency: "0.36%", references: "27494321").save!
HelixInfo.new(gene: "RGS16", variant: "rs516134", a1: "C", a2: "T", trait: "Morningness", insight: "CT individuals are more likely to identify as a morning person", recommend: "", impact: "LOW. The effect of genetics is much lower than the effect of environment.", frequency: "11%", references: "27494321").save!
HelixInfo.new(gene: "RGS16", variant: "rs516134", a1: "T", a2: "T", trait: "Morningness", insight: "TT individuals are not more likely to identify as a morning person", recommend: "", impact: "LOW. The effect of genetics is much lower than the effect of environment.", frequency: "86%", references: "27494321").save!
HelixInfo.new(gene: "VDR", variant: "rs1544410", a1: "C", a2: "C", trait: "Muscle Strength", insight: "CC individuals may have lower muscle strength", recommend: "", impact: "LOW. Training and the activities you engage in play a much larger role in your athletic performance.", frequency: "49%", references: "9421241, 17406766").save!
HelixInfo.new(gene: "VDR", variant: "rs1544410", a1: "C", a2: "T", trait: "Muscle Strength", insight: "CT individuals are unlikely to have lower muscle strength due to this variant", recommend: "", impact: "LOW. Training and the activities you engage in play a much larger role in your athletic performance.", frequency: "42%", references: "9421241, 17406766").save!
HelixInfo.new(gene: "VDR", variant: "rs1544410", a1: "T", a2: "T", trait: "Muscle Strength", insight: "TT individuals are unlikely to have lower muscle strength due to this variant", recommend: "", impact: "LOW. Training and the activities you engage in play a much larger role in your athletic performance.", frequency: "9%", references: "9421241, 17406766").save!
HelixInfo.new(gene: "GDF5", variant: "rs143383", a1: "A", a2: "A", trait: "Arthritis", insight: "AA individuals may be more likely to have osteoarthritis", recommend: "", impact: "LOW. Training and the activities you engage in play a much larger role in your injury risk than genetics.", frequency: "20.00%", references: "20633687, 20870806, 19029166").save!
HelixInfo.new(gene: "GDF5", variant: "rs143383", a1: "G", a2: "A", trait: "Arthritis", insight: "GA individuals may be more likely to have osteoarthritis", recommend: "", impact: "LOW. Training and the activities you engage in play a much larger role in your injury risk than genetics.", frequency: "50%", references: "20633687, 20870806, 19029166").save!
HelixInfo.new(gene: "GDF5", variant: "rs143383", a1: "G", a2: "G", trait: "Arthritis", insight: "GG indidividuals are not more likely to have osteoarthritis", recommend: "", impact: "LOW. Training and the activities you engage in play a much larger role in your injury risk than genetics.", frequency: "30%", references: "20633687, 20870806, 19029166").save!
HelixInfo.new(gene: "PAX8", variant: "rs62158211", a1: "T", a2: "T", trait: "Sleep Duration", insight: "TT individuals may get up to 4.5 minutes more sleep because of their genetics.", recommend: "", impact: "LOW. The effect of genetics is much lower than the effect of environment.", frequency: "2%", references: "25469926, 27992416, 27494321").save!
HelixInfo.new(gene: "PAX8", variant: "rs62158211", a1: "T", a2: "G", trait: "Sleep Duration", insight: "TG individuals may get up to 2.3 minutes more sleep because of their genetics.", recommend: "", impact: "LOW. The effect of genetics is much lower than the effect of environment.", frequency: "26%", references: "25469926, 27992416, 27494321").save!
HelixInfo.new(gene: "PAX8", variant: "rs62158211", a1: "G", a2: "G", trait: "Sleep Duration", insight: "GG individuals aren't getting any more sleep because of their genetics.", recommend: "", impact: "LOW. The effect of genetics is much lower than the effect of environment.", frequency: "72%", references: "25469926, 27992416, 27494321").save!
HelixInfo.new(gene: "Polygenic score---", variant: "", a1: "", a2: "", trait: "Hemoglobin", insight: "You may have higher levels of hemoglobin", recommend: "", impact: "LOW. Known genetic variants do not explain a large percent of the variance.", frequency: "20%", references: "23222517").save!
HelixInfo.new(gene: "Polygenic score---", variant: "", a1: "", a2: "", trait: "Hemoglobin", insight: "You may have typical levels of hemoglobin", recommend: "", impact: "LOW. Known genetic variants do not explain a large percent of the variance.", frequency: "60%", references: "23222517").save!
HelixInfo.new(gene: "Polygenic score---", variant: "", a1: "", a2: "", trait: "Hemoglobin", insight: "You may have lower levels of hemoglobin", recommend: "", impact: "LOW. Known genetic variants do not explain a large percent of the variance.", frequency: "20%", references: "23222517").save!
HelixInfo.new(gene: "Polygenic score---", variant: "", a1: "", a2: "", trait: "Mean Cell Hemoglobin", insight: "You may have higher mean cell hemoglobin", recommend: "", impact: "LOW. Known genetic variants do not explain a large percent of the variance.", frequency: "20%", references: "23222517").save!
HelixInfo.new(gene: "Polygenic score---", variant: "", a1: "", a2: "", trait: "Mean Cell Hemoglobin", insight: "You may have typical mean cell hemoglobin", recommend: "", impact: "LOW. Known genetic variants do not explain a large percent of the variance.", frequency: "60%", references: "23222517").save!
HelixInfo.new(gene: "Polygenic score---", variant: "", a1: "", a2: "", trait: "Mean Cell Hemoglobin", insight: "You may have lower mean cell hemoglobin", recommend: "", impact: "LOW. Known genetic variants do not explain a large percent of the variance.", frequency: "20%", references: "23222517").save!
HelixInfo.new(gene: "Polygenic score---", variant: "", a1: "", a2: "", trait: "Mean Cell Hemoglobin Concentration", insight: "You may have higher mean cell hemoglobin concentration", recommend: "", impact: "LOW. Known genetic variants do not explain a large percent of the variance.", frequency: "20%", references: "23222517").save!
HelixInfo.new(gene: "Polygenic score---", variant: "", a1: "", a2: "", trait: "Mean Cell Hemoglobin Concentration", insight: "You may have typical mean cell hemoglobin concentration", recommend: "", impact: "LOW. Known genetic variants do not explain a large percent of the variance.", frequency: "60%", references: "23222517").save!
HelixInfo.new(gene: "Polygenic score---", variant: "", a1: "", a2: "", trait: "Mean Cell Hemoglobin Concentration", insight: "You may have lower mean cell hemoglobin concentration", recommend: "", impact: "LOW. Known genetic variants do not explain a large percent of the variance.", frequency: "20%", references: "23222517").save!
HelixInfo.new(gene: "Polygenic score---", variant: "", a1: "", a2: "", trait: "Mean Cell Volume", insight: "You may have higher mean cell volume", recommend: "", impact: "LOW. Known genetic variants do not explain a large percent of the variance.", frequency: "20%", references: "23222517").save!
HelixInfo.new(gene: "Polygenic score---", variant: "", a1: "", a2: "", trait: "Mean Cell Volume", insight: "You may have typical mean cell volume", recommend: "", impact: "LOW. Known genetic variants do not explain a large percent of the variance.", frequency: "60%", references: "23222517").save!
HelixInfo.new(gene: "Polygenic score---", variant: "", a1: "", a2: "", trait: "Mean Cell Volume", insight: "You may have lower mean cell volume", recommend: "", impact: "LOW. Known genetic variants do not explain a large percent of the variance.", frequency: "20%", references: "23222517").save!
HelixInfo.new(gene: "Polygenic score---", variant: "", a1: "", a2: "", trait: "Packed Cell Volume", insight: "You may have higher packed cell volume", recommend: "", impact: "LOW. Known genetic variants do not explain a large percent of the variance.", frequency: "20%", references: "23222517").save!
HelixInfo.new(gene: "Polygenic score---", variant: "", a1: "", a2: "", trait: "Packed Cell Volume", insight: "You may have typical packed cell volume", recommend: "", impact: "LOW. Known genetic variants do not explain a large percent of the variance.", frequency: "60%", references: "23222517").save!
HelixInfo.new(gene: "Polygenic score---", variant: "", a1: "", a2: "", trait: "Packed Cell Volume", insight: "You may have lower packed cell volume", recommend: "", impact: "LOW. Known genetic variants do not explain a large percent of the variance.", frequency: "20%", references: "23222517").save!
HelixInfo.new(gene: "Polygenic score---", variant: "", a1: "", a2: "", trait: "Red Blood Count", insight: "You may have higher red blood count", recommend: "", impact: "LOW. Known genetic variants do not explain a large percent of the variance.", frequency: "20%", references: "23222517").save!
HelixInfo.new(gene: "Polygenic score---", variant: "", a1: "", a2: "", trait: "Red Blood Count", insight: "You may have typical red blood count", recommend: "", impact: "LOW. Known genetic variants do not explain a large percent of the variance.", frequency: "60%", references: "23222517").save!
HelixInfo.new(gene: "Polygenic score---", variant: "", a1: "", a2: "", trait: "Red Blood Count", insight: "You may have lower red blood count", recommend: "", impact: "LOW. Known genetic variants do not explain a large percent of the variance.", frequency: "20%", references: "23222517").save!
HelixInfo.new(gene: "Polygenic score---", variant: "", a1: "", a2: "", trait: "Systolic Blood Pressure", insight: "You may have higher systolic blood pressure", recommend: "There are a number of steps you can take to reduce your blood pressure. Losing weight, exercising, and reducing the amount of salt in your diet can help.", impact: "LOW. Known genetic variants do not explain a large percent of the variance.", frequency: "20%", references: "21909115").save!
HelixInfo.new(gene: "Polygenic score---", variant: "", a1: "", a2: "", trait: "Systolic Blood Pressure", insight: "You may have typical systolic blood pressure", recommend: "Keep in mind that not being at risk from genetics doesn't mean you are protected. You may still have high blood pressure. Increasing the frequency of exercise, reducing salt, and losing weight are smart choices for everyone.", impact: "LOW. Known genetic variants do not explain a large percent of the variance.", frequency: "60%", references: "21909115").save!
HelixInfo.new(gene: "Polygenic score---", variant: "", a1: "", a2: "", trait: "Systolic Blood Pressure", insight: "You may have lower systolic blood pressure", recommend: "Keep in mind that not being at risk from genetics doesn't mean you are protected. You may still have high blood pressure. Increasing the frequency of exercise, reducing salt, and losing weight are smart choices for everyone.", impact: "LOW. Known genetic variants do not explain a large percent of the variance.", frequency: "20%", references: "21909115").save!
HelixInfo.new(gene: "Polygenic score---", variant: "", a1: "", a2: "", trait: "Diastolic Blood Pressure", insight: "You may have higher diastolic blood pressure", recommend: "There are a number of steps you can take to reduce your blood pressure. Losing weight, exercising, and reducing the amount of salt in your diet can help.", impact: "LOW. Known genetic variants do not explain a large percent of the variance.", frequency: "20%", references: "21909115").save!
HelixInfo.new(gene: "Polygenic score---", variant: "", a1: "", a2: "", trait: "Diastolic Blood Pressure", insight: "You may have typical diastolic blood pressure", recommend: "Keep in mind that not being at risk from genetics doesn't mean you are protected. You may still have high blood pressure. Increasing the frequency of exercise, reducing salt, and losing weight are smart choices for everyone.", impact: "LOW. Known genetic variants do not explain a large percent of the variance.", frequency: "60%", references: "21909115").save!
HelixInfo.new(gene: "Polygenic score---", variant: "", a1: "", a2: "", trait: "Diastolic Blood Pressure", insight: "You may have lower diastolic blood pressure", recommend: "Keep in mind that not being at risk from genetics doesn't mean you are protected. You may still have high blood pressure. Increasing the frequency of exercise, reducing salt, and losing weight are smart choices for everyone.", impact: "LOW. Known genetic variants do not explain a large percent of the variance.", frequency: "20%", references: "21909115").save!
HelixInfo.new(gene: "CASR", variant: "rs1801725", a1: "G", a2: "G", trait: "Calcium", insight: "GG individuals are more likely to have average calcium levels", recommend: "Your genetics may indicate that you are more likely to have average calcium levels, but that is only if you are getting sufficient calcium in your diet.", impact: "LOW. Known genetic variants do not explain a large percent of the variance.", frequency: "82%", references: "20661308").save!
HelixInfo.new(gene: "CASR", variant: "rs1801725", a1: "G", a2: "T", trait: "Calcium", insight: "GT individuals are more likely to have average calcium levels", recommend: "Your genetics may indicate that you are more likely to have average calcium levels, but that is only if you are getting sufficient calcium in your diet.", impact: "LOW. Known genetic variants do not explain a large percent of the variance.", frequency: "17%", references: "20661308").save!
HelixInfo.new(gene: "CASR", variant: "rs1801725", a1: "T", a2: "T", trait: "Calcium", insight: "TT individuals are more likely to have increased serum calcium levels", recommend: "Your genetics may indicate that you are more likely to have increased calcium levels, but that is only if you are getting sufficient calcium in your diet.", impact: "LOW. Known genetic variants do not explain a large percent of the variance.", frequency: "1%", references: "20661308").save!

u1.helix_ids = [5, 70]
u1.save!
u2.helix_ids = [10, 30]
u2.save!
u3.helix_ids = [31, 90]
u3.save!
